theme: jekyll-theme-dinky
author:
  name: Sudarshan A. Shetty
  email: "sudarshanshetty9@gmail.com"
  github: microsud
  twitter: gutmicrobe
  
share-links-active:
  twitter: true
  facebook: true

  




