theme: jekyll-theme-dinky
title: "List of R tools for microbial census analysis"

url: 'https://microsud.github.io/' # the base hostname & protocol for your site
twitter: 'gutmicrobe'
github: 'microsud'


# Admin Settings
admin_name: 'Sudarshan_Shetty'
admin_email: 'sudarshanshetty9@gmail.com'
