theme: jekyll-theme-minimal
title: "List of R tools for microbial census analysis"

twitter: 'gutmicrobe'
github: 'microsud'


# Admin Settings
admin_name: 'Sudarshan_Shetty'
admin_email: 'sudarshanshetty9@gmail.com'
