theme: jekyll-theme-dinky
author:
  name: Sudarshan A. Shetty
  email: "sudarshanshetty9@gmail.com"
  github: 
    username: microsud
  twitter: 
    username: gutmicrobe
  
share-links-active:
  twitter: true
  facebook: true

  




