theme: jekyll-theme-dinky
title: "List of R tools for microbial census analysis"
description: "A community resource for R packages for microbiome analysis"
url: 'https://microsud.github.io/' # the base hostname & protocol for your site
nav: "true"
footer_text: 'Site modefied from © 2016 Jami Gibbs'
twitter: 'gutmicrobe'
github: 'microsud'


# Admin Settings
admin_name: 'Sudarshan_Shetty'
admin_email: 'sudarshanshetty9@gmail.com'
