theme: jekyll-theme-dinky
title: "List of R tools for microbial census analysis"
show_downloads: true
twitter: 'gutmicrobe'
github: 'microsud'


# Admin Settings
admin_name: 'Sudarshan_Shetty'
admin_email: 'sudarshanshetty9@gmail.com'
